### ISSUE TITLE
docs are outdated: NFFTPlan to plan_nfft

### ISSUE THREAD

**Issue by JeffFessler** [tknopp/NFFT.jl#45] opened 2020-12-09 02:47 UTC
I got the compat helper bump for MIRT.jl and it failed because of the breaking change from `NFFTPlan` to `plan_nfft`.  I went to the NFFT.jl docs to try to figure it out what happened but the docs still show `NFFTPlan(x, ...)`.  So I checked the source for the docs in the repo and there it has the updated usage (which is how I figured out the new API).

Not sure if the doc src needs built/pushed or if there is just some delay for some auto action to do it.

Might be nice to document the breaking change, or maybe this issue can alert others...

**Comment by tknopp** [comment] 2020-12-09 07:53
yes, this is not fully ideal, sorry! And thanks for the reminder. We will keep this issue open until the docs are fixed. I rushed the release a little bit since our high level package (MRIReco) is not building right now on master since we need releases in the underlying packages.

In the mean time you can also simply ignore the compat helper bump and wait until the docs are fixed in 0.6.1

**Comment by tknopp** [comment] 2020-12-09 09:54
@JeffFessler: Actually the issue is a different one: The docs are actually updated (see https://github.com/tknopp/NFFT.jl/blob/master/docs/src/directional.md). The issue is that Travis is not running anymore! I already contacted Travis to make clear that we are an Open Source project but we did not get a reaction.

**Comment by tknopp** [comment] 2020-12-10 09:17
the docs issue is fixed by switching to Github actions.

**Closed by tknopp** 2020-12-10 09:17 UTC
